### ISSUE TITLE
Connect to MindSphere

### ISSUE THREAD

**Issue by applea9** [siemens/opc-ua-pubsub-dotnet#20]
Hello,

Do we have tested this project to connect to MindSphere?

**Comment by Stefan-Busch** [comment]
Hi applea9,
yes, we do use this component for establishing a MindSphere connection.

**Comment by applea9** [comment]
Thanks for your answer.

We have tried many times to connect to MindSphere with this project, but no luck.

We modified SimulatedPublisher.cs and setting.json, and set correct MQTT connection parameters. After running, MQTT connection is setup successfully, and asset with the name of publishid is created. But neither aspect type nor asset type is created. It seems the meta data frame is not correctly parsed by the platform. But we don't modify meta data frame generation code.

Could you give some hints about this problem?  Thanks very much!

**Comment by ThomasSeidenbecher** [comment]
Hi applea9,

Do you send events or time series data? I assume you are aware that assets will only be created for time series values?

The problem you describe can occur if there the tenant already contains the same datatypes (e.g. MeasuredValue or CounterValue) we use, but with a different definition. This can be the case if you e.g. already sent data with an older version of this component or other publisher. Or if the datatypes you send are missing mandatory fields - maybe using the SimulatedPublisher is not the best option for Mindsphere. You can create a very simple program which just sends one MeasuredValue or an SPSEvent using the data structures from the opcuabinary, this way you can be sure that the structure is correct.
If you don't get further you can try to get support from Mindsphere and ask them why your data is rejected. Unfortunately only they can look into the logs of the broker and the OPC UA Decoder...
