### ISSUE TITLE
Unable to Decode SICAM A8000 Messages with Decoder

### ISSUE THREAD

**Issue by harrisonu** [siemens/opc-ua-pubsub-dotnet#33]
Hello Dev,
We are working on a project that requires us to read data from A8000 and decode it accordingly. However, we have not been able to get the decoder to work for the messages we are receiving. We believe we are receiving the meta message from the decoder but we get a null exception when trying to decode message.

To reproduce the error we have created 2 sample repositories
1) [https://github.com/harrisonu/SSoTFSandBox](https://github.com/harrisonu/SSoTFSandBox) - This is an exact replica of the opc-ua-pubsub-dotnet project but we added 2 new projects. A ClientConsole that connects to a rabbitmq topic and an SSToFDemoPublisher project that publishes our messages to rabbitmq

2) [https://github.com/harrisonu/opcua_testclient](https://github.com/harrisonu/opcua_testclient) - This repo just installs the opc-ua-pubsub-dotnet client Nuget package into a console app and runs the decoder on rawFiles of our messages

I have also attached a dump of the messages and error we got when we tried decoding our messages
[SSToFDecoderDump.txt](https://github.com/siemens/opc-ua-pubsub-dotnet/files/9062867/SSToFDecoderDump.txt)

Kindly help review our message and code and help suggest what we might be doing wrong and how we can get our messages to decode.

Regards
Uhunghama Harrison
Siemens CIS

**Comment by jan872** [comment]
Dear Uhunghama,

I am completely new to this (so I am not a dev and I might be completely wrong), but from some experiments with my own A8000 data, I observed the following.
If you try to read A8000 data with out setting the ```EncodingOptions``` ```LegacyFieldFlagEncoding = false``` one gets exactly the excpetion you are getting. Once I set ```LegacyFieldFlagEncoding = true``` messages are decoded without problems.

The same can be reproduced with the unit tests provided, see:
https://github.com/siemens/opc-ua-pubsub-dotnet/blob/main/src/Tests/Binary.Test/Regression_TypeA.cs#L116

Best regards
Jan

P.S.:
I could not access
https://github.com/harrisonu/opcua_testclient 
to check with your data.

**Comment by harrisonu** [comment]
Hello Jan,
Thanks for your response on this. Please were can we set the LegacyFieldFlagEncoding to true. Is it in the code (
opc-ua-pubsub-dotnet) or is it in the A8000 SICAM Config?

Looking forward to your response. Thanks again for your help so far.

Regards
Harrison

**Comment by jan872** [comment]
Hi Harrison;

it is a flag in https://github.com/siemens/opc-ua-pubsub-dotnet/blob/2a4f3a0678146f6c01f79853c4b5ec162b71f446/src/Binary/EncodingOptions.cs#L10
which in turn can be passed to:
https://github.com/siemens/opc-ua-pubsub-dotnet/blob/2a4f3a0678146f6c01f79853c4b5ec162b71f446/src/Binary/Decode/DecodeMessage.cs#L35
or 
https://github.com/siemens/opc-ua-pubsub-dotnet/blob/2a4f3a0678146f6c01f79853c4b5ec162b71f446/src/Client/Client.cs#L120

Best
Jan

**Comment by harrisonu** [comment]
Thanks a whole lot Jan, We have the messages decoding now. You have been of immerse help. The LegacyFieldFlagEncoding did the trick
