### ISSUE TITLE
Delayed Digital Data

### ISSUE THREAD

**Issue by RKatie** [siemens/opc-ua-pubsub-dotnet#50]
Hello,

We have implemented this code to successfully decode messages from the SICAM A8000. 

We are experiencing a delay of approximately 40s for the digital data (TI30) to be received in the broker. 
We had this problem too for analogue data (TI36) but found that changing the Measured value cycle in the protocol config removed the delay to the time specified however the delay for the digital data persisted.

Any guidance provided on this topic would be greatly appreciated.

Kind regards
Katie

**Comment by ThomasSeidenbecher** [comment]
Hi RKatie,
the A8000 does not use this project for its OPC UA PubSub implementation. Therefore you should address your issue at the SICAM product support.
kind regards,
Thomas
